import React, { useState } from 'react';
import { TextField, Button, Grid, Container, Typography, Paper, FormControl, InputLabel, Select, MenuItem, Box } from '@mui/material';
import axios from 'axios';
import { Outlet } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import Topbar from "../components/Topbar";

const Reports = () => {
  const [formData, setFormData] = useState({
    reportName: '',
    description: '',
    data: '',
    generatedBy: '',
    status: 'pending',
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post('http://localhost:5000/api/reports', formData);
      console.log('Report created successfully:', response.data);
      setFormData({
        reportName: '',
        description: '',
        data: '',
        generatedBy: '',
        status: 'pending',
      });
    } catch (err) {
      console.error('Error creating report:', err);
    }
  };

  return (
    <Box sx={{ display: "flex" }}>
      <Sidebar />
      <Box sx={{ flexGrow: 1, bgcolor: "#fff", minHeight: "100vh" }}>
        <Topbar />
        <Box sx={{ p: 3 }}>
          <Container maxWidth="sm" sx={{ mt: 5 }}>
                <Paper elevation={3} sx={{ padding: 3 }}>
                  <Typography variant="h4" gutterBottom color="#ff9800">
                    Create Report
                  </Typography>
                  <form onSubmit={handleSubmit}>
                    <Grid container spacing={3}>
                      <Grid item xs={12}>
                        <TextField
                          label="Report Name"
                          variant="outlined"
                          fullWidth
                          name="reportName"
                          value={formData.reportName}
                          onChange={handleChange}
                          required
                          sx={{ mb: 2 }}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextField
                          label="Description"
                          variant="outlined"
                          fullWidth
                          name="description"
                          value={formData.description}
                          onChange={handleChange}
                          sx={{ mb: 2 }}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextField
                          label="Data (JSON)"
                          variant="outlined"
                          fullWidth
                          name="data"
                          value={formData.data}
                          onChange={handleChange}
                          required
                          sx={{ mb: 2 }}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextField
                          label="Generated By"
                          variant="outlined"
                          fullWidth
                          name="generatedBy"
                          value={formData.generatedBy}
                          onChange={handleChange}
                          required
                          sx={{ mb: 2 }}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <FormControl fullWidth sx={{ mb: 2 }}>
                          <InputLabel>Status</InputLabel>
                          <Select
                            name="status"
                            value={formData.status}
                            onChange={handleChange}
                            label="Status"
                            required
                          >
                            <MenuItem value="pending">Pending</MenuItem>
                            <MenuItem value="completed">Completed</MenuItem>
                            <MenuItem value="archived">Archived</MenuItem>
                          </Select>
                        </FormControl>
                      </Grid>
                      <Grid item xs={12}>
                        <Button type="submit" variant="contained" fullWidth color="primary" sx={{ backgroundColor: '#ff9800' }}>
                          Create Report
                        </Button>
                      </Grid>
                    </Grid>
                  </form>
                </Paper>
              </Container>
          <Outlet />
        </Box>
      </Box>
    </Box>
  );
};

export default Reports;
